name: fk_logs
description: Loggy extension to use 'developer.log' with pretty printer in Flutter
version: 2.0.0
homepage: http://github.com/flutter-fast-kit/fk_logs
repository: http://github.com/flutter-fast-kit/fk_logs

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.26.0
  dio: ^4.0.0
  stack_trace: '>=1.10.0 <2.0.0'